// styles/LoginScreenStyles.js
import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const LoginScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  backgroundGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  decorativeCircle1: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: '#5CE1E6',
    opacity: 0.03,
    top: -100,
    left: -100,
  },
  decorativeCircle2: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#00adb5',
    opacity: 0.05,
    bottom: -50,
    right: -50,
  },
  decorativeCircle3: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: '#5CE1E6',
    opacity: 0.03,
    bottom: height * 0.3,
    left: -50,
  },
  topWave: {
    position: 'absolute',
    top: 0,
  },
  keyboardAvoid: {
    flex: 1,
    justifyContent: 'center',
  },
  contentContainer: {
    paddingHorizontal: 30,
    alignItems: 'center',
    width: '100%',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(92, 225, 230, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(92, 225, 230, 0.3)',
    marginBottom: 20,
    shadowColor: '#5CE1E6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10,
  },
  appName: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
    letterSpacing: 2,
    marginBottom: 8,
  },
  divider: {
    width: 100,
    height: 3,
    backgroundColor: '#5CE1E6',
    borderRadius: 2,
    marginVertical: 10,
  },
  tagline: {
    fontSize: 16,
    color: '#a0a0c0',
    textAlign: 'center',
    marginTop: 5,
    fontStyle: 'italic',
  },
  featuresContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 40,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(92, 225, 230, 0.1)',
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  featureText: {
    color: '#e0e0ff',
    fontSize: 16,
    marginLeft: 15,
  },
  authButton: {
    width: '100%',
    borderRadius: 25,
    overflow: 'hidden',
    shadowColor: '#5CE1E6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
    marginBottom: 30,
  },
  buttonGradient: {
    flexDirection: 'row',
    paddingVertical: 18,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonIcon: {
    marginRight: 12,
  },
  authButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  infoContainer: {
    alignItems: 'center',
  },
  infoText: {
    color: '#a0a0c0',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 20,
  },
  securityNote: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(92, 225, 230, 0.1)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(92, 225, 230, 0.2)',
  },
  securityText: {
    color: '#5CE1E6',
    fontSize: 12,
    marginLeft: 8,
    fontWeight: '500',
  },
});

export default LoginScreenStyles;